#!/usr/bin/env node

var fs = require('fs')
  , ini = require('multi-ini')

var makeBackup = true
var removeMissingFiles = true
var removeEarlierDuplicates = true
var removeLaterDuplicates = false
// BUG: Because we process the items in string-order rather than numeric order, we will sometimes be incorrect about which entry is earlier/later

// I did try require('ini') but it didn't write back exactly what was read, notably adding additional '"'s and '\'s to the ByteArray value of header_state keys
//
// multi-ini surrounds every written value with quotes, but SMPlayer doesn't seem to mind this.  It removes the unnecessary ones, and ends up with a file that looks much like the original.
// multi-ini does not write out keys with empty values, but SMPlayer restores these (although only for video files which exist).

var inFile = require('os').homedir() + '/.config/smplayer/playlist.ini'
var tmpFile = `${inFile}.NEW`
var backupFile = `${inFile}.${new Date().toISOString().replace(/-/g, '').replace(/T/, '-').replace(/:/g, '').replace(/[.].*/, '')}`

var config = ini.read(inFile, 'utf-8')
//console.log('config:', config)

// The keys looke like this:
//     items\1\item_0_duration
//     items\1\item_0_filename
//     items\1\item_0_name
//     items\1\item_0_params
//     items\1\item_0_shuffle
// They cotain two numbers, the first always one larger than the second.

// There may be entries in the playlist beyond the numItems, which SMPlayer does not actually show
// We had better ignore these
var numItems = Number(config.playlist_contents['items\\size'])
//console.log('numItems:', numItems)

var keysToKeep = []

var earlierPrefixesByFilename = {}

// Unfortunately because keys are string-indexed, we will not be processing them in numerical order
for (var key in config.playlist_contents) {
  if (key.startsWith('items\\') && key.endsWith('_filename')) {
    var prefix = key.replace(/_filename$/, '')
    var keyNum = getKeyNumFromPrefix(prefix)
    var filename = config.playlist_contents[key]
    //console.log('[%s] %s:', keyNum, filename)

    if (Number(keyNum) >= numItems) {
      // This is stored in the array but its not one of those SMPlayer is actually showing.
      // We had better skip it, otherwise it might be detected as a later duplicate, producing unexpected results.
      continue
    }

    var keepThisOne

    if (removeMissingFiles && !fs.existsSync(filename)) {
      console.log(`Removing missing file ${keyNum}: ${filename}`)
      keepThisOne = false
    } else if (removeEarlierDuplicates && earlierPrefixesByFilename[filename]) {
      var earlierPrefix = earlierPrefixesByFilename[filename]
      var earlierKeyNum = getKeyNumFromPrefix(earlierPrefix)
      console.log(`Removing earlier duplicate ${earlierKeyNum}: ${filename}`)
      keysToKeep = keysToKeep.filter(keyN => keyN !== earlierKeyNum)
      removeEntryWithPrefix(earlierPrefix)
      keepThisOne = true
    } else if (removeLaterDuplicates && earlierPrefixesByFilename[filename]) {
      console.log(`Removing later duplicate ${keyNum}: ${filename}`)
      keepThisOne = false
    } else {
      // We will keep this one
      keepThisOne = true
    }

    if (keepThisOne) {
      //console.log('keyNum:', keyNum)
      keysToKeep.push(keyNum)
      earlierPrefixesByFilename[filename] = prefix
    } else {
      removeEntryWithPrefix(prefix)
    }
  }
}

function getKeyNumFromPrefix(prefix) {
  return prefix.replace(/.*_([0-9]*)$/, '$1')
}

function removeEntryWithPrefix(prefix) {
  // Remove all keys matching this one
  //console.log('prefix:', prefix)
  //console.log(`Removing entry: ${prefix}`)
  for (var key2 in config.playlist_contents) {
    if (key2.startsWith(prefix + '_')) {
      //console.log('Deleting', key2)
      delete config.playlist_contents[key2]
    }
  }
}

// Now the keys which we are going to keep need to be renumbered (to fill in the gaps we created)
// First we must sort the keys numerically, because they are strings (currently "10" is actually coming before "2")
keysToKeep.sort((a, b) => Number(a) - Number(b))
//console.log('keysToKeep:', keysToKeep)
// After renaming a key, we don't copy immediately into the existing object, because due to ordering we may overwrite an existing key!
// Instead we collect all the new key-value pairs, and only copy them over at the end.
var newData = {}
for (var key in config.playlist_contents) {
  var keyNum = key.replace(/.*_([0-9]*)_\w*/, '$1')
  var newIndex = keysToKeep.indexOf(keyNum)
  //console.log(`${keyNum} -> ${newIndex}`)
  if (newIndex >= 0) {
    var arr1 = key.split('\\')
    arr1[1] = String(newIndex + 1)
    var arr2 = arr1.join('\\').split('_')
    arr2[1] = String(newIndex)
    var newKey = arr2.join('_')
    //console.log(`${key} -> ${newKey}`)
    newData[newKey] = config.playlist_contents[key]
    delete config.playlist_contents[key]
  }
}
for (var key in newData) {
  config.playlist_contents[key] = newData[key]
}

// The original ini had `items\size=1311`
// Although curiously there were more items listed in the ini file
// Anyway this is the number that SMPlayer shows in its playlist
config.playlist_contents['items\\size'] = String(keysToKeep.length)
console.log('Remaining entries:', keysToKeep.length)

ini.write(tmpFile, config)

if (makeBackup) {
  fs.copyFileSync(inFile, backupFile)
  console.log('Backup made at:', backupFile)
}

fs.renameSync(tmpFile, inFile)

